version: "3"

services:
  #react-app:
    #build: docker/react-app
    #tty: true
    #volumes:
      #- type: "bind"
        #source: ./next-app
        #target: /next-app
    #stdin_open: true
    #ports:
        #- "3000:3000"
    #user: root

  postgresql:
    image: postgres:10.5
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/init/:/docker-entrypoint-initdb.d
      - C:\Users\${USER}\Volume\study_postgresql\postgres:/var/lib/postgresql/data
    environment:
      PSOTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encodig=UTF-8"
    hostname: postgres
    user: root
    environment:
      TZ: "Asia/Tokyo"

  pgadmin4:
    image: dpage/pgadmin4:3.3
    ports:
      - 80:80
      - 5050:5050
      - 443:443
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgresql
    hostname: pgadmin4

networks:
  default:
    ipam:
      config:
        - subnet: 172.19.0.0/24