version: "3"

services:
  react-app:
    build: docker/react-app
    tty: true
    volumes:
      - "./react-app:/react-app:rw"
    stdin_open: true
    ports:
      - "3000:3000"
    user: root

  express-app:
    build: docker/express-app
    tty: true
    volumes:
      - "./express-app:/express-app:rw"
    stdin_open: true
    ports:
      - "5000:5000"
    user: root